import Mock from "mockjs";

let List = []

export default {
   getStatisticalData:()=>{
    for (let i = 0; i < 7; i++) {
        List.push(
            Mock.mock({
                苹果:Mock.Random.float(100,8000,0,0),
                vivo:Mock.Random.float(100,8000,0,0),
                oppo:Mock.Random.float(100,8000,0,0),
                魅族:Mock.Random.float(100,8000,0,0),
                三星:Mock.Random.float(100,8000,0,0),
                小米:Mock.Random.float(100,8000,0,0),
            })
        )
        
    }
    return {
        code:20000,
        data:{
            videoData:[
               {
                name:'小米',
                value:2999
               },
               {
                name:'苹果',
                value:8999
               },
               {
                name:'vivo',
                value:3999
               },
               {
                name:'oppo',
                value:3999
               },
               {
                name:'魅族',
                value:3599
               },
               {
                name:'三星',
                value:7999
               },
            ],
            userData:[
                {
                    date:"周一",
                    new:5,
                    active:200
                },
                {
                    date:"周二",
                    new:10,
                    active:500
                },
                {
                    date:"周三",
                    new:15,
                    active:400
                },
                {
                    date:"周四",
                    new:10,
                    active:200
                },
                {
                    date:"周五",
                    new:7,
                    active:300
                },
                {
                    date:"周六",
                    new:5,
                    active:200
                },
                {
                    date:"周日",
                    new:20,
                    active:700
                },
            ],
            orderData:{
                date:['20230302','20230303','20230304','20230305','20230306','20230307','20230308',],
                data:List
            },
            tableData:[
                {
                    name:'oppo',
                    todayBuy:500,
                    monthBuy:3500,
                    totalBuy:20000
                },
                {
                    name:'vivo',
                    todayBuy:300,
                    monthBuy:2000,
                    totalBuy:22000
                },
                {
                    name:'苹果',
                    todayBuy:1000,
                    monthBuy:5000,
                    totalBuy:68000
                },
                {
                    name:'三星',
                    todayBuy:200,
                    monthBuy:1500,
                    totalBuy:15000
                },
                {
                    name:'魅族',
                    todayBuy:250,
                    monthBuy:2000,
                    totalBuy:30000
                },
                {
                    name:'小米',
                    todayBuy:2000,
                    monthBuy:9000,
                    totalBuy:120000
                },
            ]
        }
    }
   }
}